'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class View
    
    '''<summary>
    '''bk_aj_nav_avatar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bk_aj_nav_avatar As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''bb_aj_userskinsetting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bb_aj_userskinsetting As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
